import { GradeWithSubject } from "@/db/schema";
import { AverageWithSubject } from "@/types/types";

export const MOCKDATA: {
  data: GradeWithSubject[];
  averageData: AverageWithSubject[];
  failingData: (data: AverageWithSubject[]) => AverageWithSubject[];
  passingData: (data: AverageWithSubject[]) => AverageWithSubject[];
} = {
  data: [
    {
      grades: {
        id: 1,
        value: 52,
        subject_fk: 3,
        description: "Trigonometry",
        weight: 1,
        date: new Date("2024-09-09T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 3,
        name: "Maths",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 2,
        value: 79,
        subject_fk: 3,
        description: "Statistics I",
        weight: 1,
        date: new Date("2024-08-21T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 3,
        name: "Maths",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 3,
        value: 61,
        subject_fk: 3,
        description: "Calculus",
        weight: 2,
        date: new Date("2024-09-21T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 3,
        name: "Maths",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 4,
        value: 85,
        subject_fk: 2,
        description: "Poetry Analysis",
        weight: 1,
        date: new Date("2024-09-02T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 2,
        name: "English",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 5,
        value: 77,
        subject_fk: 2,
        description: "Grammar Unit 8",
        weight: 1,
        date: new Date("2024-09-23T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 2,
        name: "English",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 6,
        value: 72,
        subject_fk: 2,
        description: 'Essay "Pollution"',
        weight: 1,
        date: new Date("2024-08-25T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 2,
        name: "English",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 7,
        value: 75,
        subject_fk: 4,
        description: "Fitness Test",
        weight: 1,
        date: new Date("2024-09-16T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 4,
        name: "PE",
        weight: 0,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 8,
        value: 55,
        subject_fk: 4,
        description: "20 Minutes Run",
        weight: 1,
        date: new Date("2024-09-14T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 4,
        name: "PE",
        weight: 0,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 9,
        value: 65,
        subject_fk: 1,
        description: "Fiscal Policy",
        weight: 0.75,
        date: new Date("2024-09-16T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 1,
        name: "Economy",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 10,
        value: 54,
        subject_fk: 1,
        description: "International trade",
        weight: 1,
        date: new Date("2024-09-24T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 1,
        name: "Economy",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 11,
        value: 45,
        subject_fk: 1,
        description: "Inflation",
        weight: 1,
        date: new Date("2024-09-13T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 1,
        name: "Economy",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 12,
        value: 54,
        subject_fk: 5,
        description: "Mechanics",
        weight: 1,
        date: new Date("2024-08-31T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 5,
        name: "Physics",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 13,
        value: 58,
        subject_fk: 5,
        description: "Dynamics",
        weight: 1,
        date: new Date("2024-09-13T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 5,
        name: "Physics",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 14,
        value: 53,
        subject_fk: 5,
        description: "Energy",
        weight: 1,
        date: new Date("2024-09-24T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 5,
        name: "Physics",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      grades: {
        id: 15,
        value: 61,
        subject_fk: 5,
        description: "Statics",
        weight: 1,
        date: new Date("2024-09-19T22:00:00.000Z"),
        category_fk: 0,
        userId: "0",
      },
      subjects: {
        id: 5,
        name: "Physics",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
  ],
  averageData: [
    {
      average: {
        subjectId: 1,
        gradeAverage: 53.727,
        gradeSum: 164,
        gradeWeightedSum: 147.75,
        gradeWeightedAmount: 2.75,
        gradeAmount: 3,
        passing: false,
      },
      subject: {
        id: 1,
        name: "Economy",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      average: {
        subjectId: 2,
        gradeAverage: 78,
        gradeSum: 234,
        gradeWeightedSum: 234,
        gradeWeightedAmount: 3,
        gradeAmount: 3,
        passing: true,
      },
      subject: {
        id: 2,
        name: "English",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      average: {
        subjectId: 3,
        gradeAverage: 63.25,
        gradeSum: 192,
        gradeWeightedSum: 253,
        gradeWeightedAmount: 4,
        gradeAmount: 3,
        passing: true,
      },
      subject: {
        id: 3,
        name: "Maths",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      average: {
        subjectId: 4,
        gradeAverage: 65,
        gradeSum: 130,
        gradeWeightedSum: 130,
        gradeWeightedAmount: 2,
        gradeAmount: 2,
        passing: true,
      },
      subject: {
        id: 4,
        name: "PE",
        weight: 0,
        category_fk: 0,
        userId: "0",
      },
    },
    {
      average: {
        subjectId: 5,
        gradeAverage: 56.5,
        gradeSum: 226,
        gradeWeightedSum: 226,
        gradeWeightedAmount: 4,
        gradeAmount: 4,
        passing: false,
      },
      subject: {
        id: 5,
        name: "Physics",
        weight: 1,
        category_fk: 0,
        userId: "0",
      },
    },
  ],
  failingData: (data: AverageWithSubject[]) =>
    data.filter(
      (average: AverageWithSubject) => average.average?.passing === false
    ),
  passingData: (data: AverageWithSubject[]) =>
    data.filter((average: AverageWithSubject) => average.average?.passing),
};
