name: Docker Build CI

on:
  push:
    branches: "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: docker_build
        run: |
          docker build -t grade-calculator .
          echo "BUILD_STATUS=success" >> $GITHUB_ENV

      - name: Print success message
        if: steps.docker_build.outputs.BUILD_STATUS == 'success'
        run: echo "✅ Docker build test passed!"
